platform :ios, '8.0'

target 'SZ_AFN-RAC_Network' do

  pod 'ReactiveObjC'
  pod 'AFNetworking',                       '3.1.0'
  pod 'YYKit',                              '1.0.9'
  # 钥匙串存储
  pod 'SAMKeychain'                       , '1.5.2'
  pod 'MJExtension'                       , '3.0.13'
  # 加密
  pod 'CocoaSecurity'                     , '1.2.4'

end

